package riot.riotapi.dtos.match;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ChallengesDTO {
    @JsonProperty("12AssistStreakCount")
    private Integer _12AssistStreakCount;
    private Integer abilityUses;
    private Integer acesBefore15Minutes;
    private Integer alliedJungleMonsterKills;
    private Integer baronTakedowns;
    private Integer blastConeOppositeOpponentCount;
    private Integer bountyGold;
    private Integer buffsStolen;
    private Integer completeSupportQuestInTime;
    private Double controlWardTimeCoverageInRiverOrEnemyHalf;
    private Integer controlWardsPlaced;
    private Double damagePerMinute;
    private Double damageTakenOnTeamPercentage;
    private Integer dancedWithRiftHerald;
    private Integer deathsByEnemyChamps;
    private Integer dodgeSkillShotsSmallWindow;
    private Integer doubleAces;
    private Integer dragonTakedowns;
    private Double earliestDragonTakedown;
    private Integer earlyLaningPhaseGoldExpAdvantage;
    private Double effectiveHealAndShielding;
    private Integer elderDragonKillsWithOpposingSoul;
    private Integer elderDragonMultikills;
    private Integer enemyChampionImmobilizations;
    private Integer enemyJungleMonsterKills;
    private Integer epicMonsterKillsNearEnemyJungler;
    private Integer epicMonsterKillsWithin30SecondsOfSpawn;
    private Integer epicMonsterSteals;
    private Integer epicMonsterStolenWithoutSmite;
    private Integer firstTurretKilled;
    private Double firstTurretKilledTime;
    private Integer flawlessAces;
    private Integer fullTeamTakedown;
    private Double gameLength;
    private Integer getTakedownsInAllLanesEarlyJungleAsLaner;
    private Double goldPerMinute;
    private Integer hadOpenNexus;
    private Integer highestChampionDamage;
    private Integer immobilizeAndKillWithAlly;
    private Integer initialBuffCount;
    private Integer initialCrabCount;
    private Double jungleCsBefore10Minutes;
    private Integer junglerTakedownsNearDamagedEpicMonster;
    private Integer kTurretsDestroyedBeforePlatesFall;
    private Double kda;
    private Integer killAfterHiddenWithAlly;
    private Double killParticipation;
    private Integer killedChampTookFullTeamDamageSurvived;
    private Integer killingSprees;
    private Integer killsNearEnemyTurret;
    private Integer killsOnOtherLanesEarlyJungleAsLaner;
    private Integer killsOnRecentlyHealedByAramPack;
    private Integer killsUnderOwnTurret;
    private Integer killsWithHelpFromEpicMonster;
    private Integer knockEnemyIntoTeamAndKill;
    private Integer landSkillShotsEarlyGame;
    private Integer laneMinionsFirst10Minutes;
    private Integer laningPhaseGoldExpAdvantage;
    private Integer legendaryCount;
    private Integer lostAnInhibitor;
    private Double maxCsAdvantageOnLaneOpponent;
    private Integer maxKillDeficit;
    private Integer maxLevelLeadLaneOpponent;
    private Integer mejaisFullStackInTime;
    private Double moreEnemyJungleThanOpponent;
    private Integer multiKillOneSpell;
    private Integer multiTurretRiftHeraldCount;
    private Integer multikills;
    private Integer multikillsAfterAggressiveFlash;
    private Integer mythicItemUsed;
    private Integer outerTurretExecutesBefore10Minutes;
    private Integer outnumberedKills;
    private Integer outnumberedNexusKill;
    private Integer perfectDragonSoulsTaken;
    private Integer perfectGame;
    private Integer pickKillWithAlly;
    private Integer playedChampSelectPosition;
    private Integer poroExplosions;
    private Integer quickCleanse;
    private Integer quickFirstTurret;
    private Integer quickSoloKills;
    private Integer riftHeraldTakedowns;
    private Integer saveAllyFromDeath;
    private Integer scuttleCrabKills;
    private Integer skillshotsDodged;
    private Integer skillshotsHit;
    private Integer snowballsHit;
    private Integer soloBaronKills;
    private Integer soloKills;
    private Integer stealthWardsPlaced;
    private Integer survivedSingleDigitHpCount;
    private Integer survivedThreeImmobilizesInFight;
    private Integer takedownOnFirstTurret;
    private Integer takedowns;
    private Integer takedownsAfterGainingLevelAdvantage;
    private Integer takedownsBeforeJungleMinionSpawn;
    private Integer takedownsFirstXMinutes;
    private Integer takedownsInAlcove;
    private Integer takedownsInEnemyFountain;
    private Integer teamBaronKills;
    private Double teamDamagePercentage;
    private Integer teamElderDragonKills;
    private Integer teamRiftHeraldKills;
    private Integer tookLargeDamageSurvived;
    private Integer turretPlatesTaken;
    private Integer turretTakedowns;
    private Integer turretsTakenWithRiftHerald;
    private Integer twentyMinionsIn3SecondsCount;
    private Integer twoWardsOneSweeperCount;
    private Integer unseenRecalls;
    private Double visionScoreAdvantageLaneOpponent;
    private Double visionScorePerMinute;
    private Integer wardTakedowns;
    private Integer wardTakedownsBefore20M;
    private Integer wardsGuarded;
    private Integer highestWardKills;
    private Integer junglerKillsEarlyJungle;
    private Integer killsOnLanersEarlyJungleAsJungler;
    private Integer soloTurretsLategame;
    private Double earliestBaron;
    private Integer highestCrowdControlScore;
    private Integer teleportTakedowns;
    private Integer fasterSupportQuestCompletion;
}
